# Generated by Django 4.2.20 on 2025-03-18 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('has_children', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.CharField(choices=[('confirmed', 'Confirmed'), ('RAC', 'RAC'), ('waiting', 'Waiting')], max_length=10)),
                ('berth_type', models.CharField(blank=True, choices=[('lower', 'Lower Berth'), ('upper', 'Upper Berth'), ('RAC', 'RAC Side-Lower')], max_length=10, null=True)),
                ('seat_number', models.IntegerField(blank=True, null=True)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railway_ticket_reservation.passenger')),
            ],
        ),
    ]
