# Generated by Django 4.2.20 on 2025-03-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway_ticket_reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='berth_type',
            field=models.CharField(blank=True, choices=[('lower', 'Lower'), ('upper', 'Upper'), ('side_lower', 'Side Lower')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('RAC', 'RAC'), ('waiting', 'Waiting'), ('cancelled', 'Cancelled')], max_length=10),
        ),
    ]
